<link rel="stylesheet" href="/stylesheets/smart-template/normalize.min.css">
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700,300' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="/stylesheets/smart-template/bootstrap.min.css">
<link rel="stylesheet" href="/stylesheets/smart-template/font-awesome.min.css">

<!-- video plugin css -->
<link rel="stylesheet" href="/stylesheets/online-training/video-js.css">
<!-- end video plugin css -->

<link rel="stylesheet" href="/stylesheets/smart-template/screen.css">
<link rel="stylesheet" href="/stylesheets/online-training/style.css">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>