{module_webapps id="37456" filter="item" itemId="6679077" collection = "logo" template = ""}
<!--<header class="site-header-wrap">
  <div class="site-header"> <a href = "/"><img alt="" src="{{logo.items[0].logo}}" class="site-header__logo"/></a> </div>
</header>-->
<div class="navbar-wrapper">
    <div class="container-fluid">
        <nav class="navbar">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/"><img src="{{logo.items[0].logo}}"></a>
                </div>
                <!--<div id="navbar" class="navbar-collapse collapse">                    
                    <ul class="nav navbar-nav pull-right">                        
                        <li class=""><a href="#">Logout</a></li>
                    </ul>
                </div>-->
                {module_menu version="2" menuId="1911315" moduleTemplateGroup="MainMenu"}
            </div>
        </nav>
    </div>
</div>